# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b25e04526f59632ecb24cc4eabe9081856f973b347c8f83e6bf29a92fd749431d62a1d226074141d3e3fd2cd8663ea67b708e546c44a6a99ed5e19b06acbb9b2

test:
  secret_key_base: b36b8099d2a5491a6b6e399b573b3a593e0357eb3fe2fe86f4a44ae5781227a93f5db20a88449a382f1d6b682729e8c55e16a45cd4e8576862cb904b59a05fc8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
